[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.pdo_mysql",
    "php82Extensions.gd",
    "php82Extensions.mbstring",
    "php82Extensions.xml",
    "php82Extensions.curl",
    "php82Extensions.zip",
    "php82Extensions.bcmath",
    "php82Extensions.exif",
    "php82Extensions.tokenizer",
    "php82Extensions.fileinfo",
    "nodejs_20",
    "nodePackages.npm",
    "php82Packages.composer"
]

[phases.build]
cmds = [
    "npm ci",
    "npm run build",
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan route:clear && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"